dist: bionic
language: java
jdk: openjdk11

addons:
  apt:
    packages:
    - python3.7
    - python3.7-dev

cache:
  directories:
  - $HOME/.cache/pants

script:
- ./pants compile examples/client:client_proto
- ./pants run examples/simple:main 
