scalapb_library(
  name='client_proto',
  sources=['./client.proto'],
  dependencies=[
    '//examples/simple:simple_proto',
    '3rdparty/jvm:scalapb-runtime'
  ],
  imports=[
    '3rdparty/jvm:scalapb-runtime'
  ]
)

